// File generated by hand from the Firebase console config files
// (android/app/google-services.json, ios/Runner/GoogleService-Info.plist)
// for project doctor-appointment-app-84847.
//
// Web has not been registered as a Firebase app yet — register one in the
// Firebase console and regenerate this file (ideally via `flutterfire
// configure`, which keeps all platforms in sync) before running on web.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'register a web app in the Firebase console and run '
        '`flutterfire configure` to generate its options.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for '
          '$defaultTargetPlatform - run `flutterfire configure` to add it.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWvXEv9piCfvhsVUjLji1Kil0fZSaWMs',
    appId: '1:758398004020:android:e9652639d5f5f027afd361',
    messagingSenderId: '758398004020',
    projectId: 'doctor-appointment-app-84847',
    storageBucket: 'doctor-appointment-app-84847.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQxGJENH-Yd4IAhEE53_M0xivjLcPJ5KM',
    appId: '1:758398004020:ios:e9f321de547a99c0afd361',
    messagingSenderId: '758398004020',
    projectId: 'doctor-appointment-app-84847',
    storageBucket: 'doctor-appointment-app-84847.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );
}
