// File generated by hand from the Firebase console config
// (android/app/google-services.json, ios/Runner/GoogleService-Info.plist,
// and the web app's firebaseConfig snippet) for project
// doctor-appointment-app-84847.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for '
          '$defaultTargetPlatform - run `flutterfire configure` to add it.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC793fVPMRw-kU1aKJs35tyavnvZw4vg9U',
    authDomain: 'doctor-appointment-app-84847.firebaseapp.com',
    projectId: 'doctor-appointment-app-84847',
    storageBucket: 'doctor-appointment-app-84847.firebasestorage.app',
    messagingSenderId: '758398004020',
    appId: '1:758398004020:web:b8ee9ee9970b44e2afd361',
    measurementId: 'G-7CJ3PGSYN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWvXEv9piCfvhsVUjLji1Kil0fZSaWMs',
    appId: '1:758398004020:android:e9652639d5f5f027afd361',
    messagingSenderId: '758398004020',
    projectId: 'doctor-appointment-app-84847',
    storageBucket: 'doctor-appointment-app-84847.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQxGJENH-Yd4IAhEE53_M0xivjLcPJ5KM',
    appId: '1:758398004020:ios:e9f321de547a99c0afd361',
    messagingSenderId: '758398004020',
    projectId: 'doctor-appointment-app-84847',
    storageBucket: 'doctor-appointment-app-84847.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );
}
